"""환경변수 이름과 구성 파일이 없을 때 사용할 기본값."""

# 배포 환경에서 JSON 설정을 덮어쓸 때 사용하는 환경변수 키다.
ENV_OLLAMA_BASE_URL = "OLLAMA_BASE_URL"
ENV_OLLAMA_MODEL = "OLLAMA_MODEL"
ENV_REQUEST_TIMEOUT_SECONDS = "REQUEST_TIMEOUT_SECONDS"
ENV_MAX_TOOL_ROUNDS = "MAX_TOOL_ROUNDS"
ENV_MCP_SERVERS_JSON = "MCP_SERVERS_JSON"

# 개발 환경에서도 즉시 실행할 수 있는 보수적인 로컬 기본값이다.
DEFAULT_OLLAMA_BASE_URL = "http://127.0.0.1:11434"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 60.0
DEFAULT_MAX_TOOL_ROUNDS = 3
DEFAULT_MCP_TIMEOUT_SECONDS = 15.0
